### PR TITLE
Letters Repeated

### PR DESCRIPTION
**Pull request by Pidek**
Letters Rep

### CODE REVIEW

**Comment by aromeronavia** [comment]
Good job tho, I've seen a great progress from your side.
Let me share with you another solution. Analyze it and tell me the differences.
Not going to include code but just the idea.
1) Iterate all the characters in a string and put them in a single map, using the character as the key and the repetitions as the value.
2) Iterate the map with the keys, and if the `map[key]` is greater than 1, print the key and the value, otherwise do nothing.

**Comment by Pidek** [comment]
all the characters are stored as keys with its values ( even they are not
repeated) in a map and you just select the values repeated with the
condition  value>1, then you print the key and its value.

The difference is just you stored al the characters as keys in a map, my
program just stored the characters that are repeated.
To print the repeated characters my code works better but, to filter
repeated and not repeated characaters your idea is better.

2016-11-22 20:30 GMT-06:00 Alberto Romero notifications@github.com:

**Comment by aromeronavia** [comment]
Actually you do both. You store all the characters in a map and all the repeated in another map.
Not saying it's a bad approach, it actually solves the problem. Just wanna put you to think in those kind of details.

I'm ok with merging this PR to master :+1:

**Comment by aromeronavia** [comment]
Remember to close the issue in github once you have merged.

**Pull request merged**
